name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Restore Blade keystore (for app signing)
        run: |
          echo "${{ secrets.BLADE_KEYSTORE }}" > blade-keystore.b64
          base64 -d blade-keystore.b64 > blade-keystore.jks

      - name: Restore debug keystore (for debug configurations)
        run: |
          echo "${{ secrets.DEBUG_KEYSTORE }}" > debug.b64
          mkdir ~/.android
          base64 -d debug.b64 > ~/.android/debug.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -PreleaseStorePassword=${{ secrets.RELEASE_STORE_PASSWORD }} -PreleaseKeyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}
